spring:
  application:
    name: report-ms
  profiles:
    active: default # Seleccionamos al "profile" de "default"
  config:
    import: "optional:configserver:http://localhost:7777"
  jpa:
    open-in-view: false
server:
  servlet:
    context-path: /report-ms
  port: 7070
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/