spring:
  # Por medio de ${} usamos los valores de cada propiedad del repositorio de remoto, con el profile "default" en este caso.
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    # Asignamos el timeout a 20 000 milisegundos y el pool size de 5
    hikari:
      maximum-pool-size: ${db..maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
  application:
    name: companies-crud
  profiles:
    active: default # Seleccionamos al "profile" de "default"
  config:
  # Indicamos la ruta de donde se importaran las configuraciones en caso el "servidor de configuraciones" falle de forma remota
    import: "optional:configserver:http://localhost:7777"
  # Configuracion para evitar el warning de "spring.jpa.open-in-view to disable this warning" en el terminal,
  # el cual al deshabilitarlo permite manejar excepcinoes de inicializacion perezosa como "LazyInitializationException" de forma mas efectiva
  jpa:
    open-in-view: false
server:
  servlet:
    context-path: /companies-crud
  # Con el puerto en "0" genera un puerto aleatorio para la instancia ejecutada. Ejemplo 49725
  # Opcion 1:
  ##port: 0
  # Opcion 2:
  port: ${PORT:0}
  ##port: 8081
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  # Personalizamos el nombre de la instancia en Eureka, visible en el dashboard web y que normalmente es autogenerada
  # ${spring.application.name} : Invoca al nombre del microservicio, asignado arriba
  # {random.value} : Propio de spring para asignar una cadena alfanumerica aleatoria
  # Cada instancia quedara por ejemplo algo asi como: companies-crud:6300735079e1baeb6475e6c896c6ed0a
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    # Configuracion (obligatorio en caso el servidor eureka se encuentre en otra maquina con IPs distintas) indicando cual es nuestro servidor eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/