server:
  port: 7777
spring:
  application:
    name: config-server
  profiles:
    active: default # Seleccionamos al "profile" de "default"
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/rafaelminaya/msvc-companies-config-data.git
          uri: git@github.com:rafaelminaya/msvc-companies-config-data.git
          default-label: main # Indicamos que "main" sera la rama por defecto a conectarse
          clone-on-start: true # Indicamos que va a clonar el "repositorio remoto" una vez ejecutado este proyecto. Por defecto es false
          # 1 Opcion : Usando credenciales usuario y password(token de GitHub)
          # 2 Opcion : Usando el SSH-key de GitHub
          ignore-local-ssh-settings: true # cambiaos a true para ignorar los seetings del ssh
          host-key-algorithm: ecdsa-sha2-nistp256 # Debemos indicar el nombre del algoritmo que usamos al generar el SSH
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= # Este "host-key" fue generado en el terminal
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: AES-128-CBC,6604EA6DEB269C30188E3E91D1537389
            
            sqfL61Y6QPYiccabVMEknbnJbG9P+O50YnB1pdO/x4/3EMOnhPFEuQkTlYAgcmQw
            d1jYOIzRMGbwFbgaL28ha0Dk/LORuzXyA1+tvHQwo+JpRkFRmRgLKdwtAMgrZiWU
            x5/VZMue5NqeCfProDlQTLA7bmLnucG0/NHPJDnf4mk=
            -----END EC PRIVATE KEY-----
          passphrase: rminaya # Indicamos la password que se escribio para generar los "SSH-key" publico y privado
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      # Configuracion (obligatorio en caso el servidor eureka se encuentre en otra maquina con IPs distintas) indicando la ruta de nuestro servidor eureka
      defaultZone: http://localhost:8761/eureka/