server:
  port: 7777
spring:
  application:
    name: config-server
  profiles:
    active: default # Seleccionamos al "profile" de "default"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaelminaya/msvc-companies-config-data.git
          #uri: git@github.com:rafaelminaya/msvc-companies-config-data.git
          default-label: main # Indicamos que "main" sera la rama por defecto a conectarse
          clone-on-start: true # Indicamos que va a clonar el "repositorio remoto" una vez ejecutado este proyecto. Por defecto es false
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      # Configuracion (obligatorio en caso el servidor eureka se encuentre en otra maquina con IPs distintas) indicando la ruta de nuestro servidor eureka
      defaultZone: http://localhost:8761/eureka/